  postgrestest:
    build:
      context: docker/blocks/postgres_tests
    environment:
      POSTGRES_USER: smartemstest
      POSTGRES_PASSWORD: smartemstest
    ports:
      - "5432:5432"
    tmpfs: /var/lib/postgresql/data:rw