#!/bin/sh

set -e

[ -f /etc/default/smartems-server ] && . /etc/default/smartems-server

IS_UPGRADE=false


case "$1" in
	configure)
	[ -z "$SMARTEMS_USER" ] && SMARTEMS_USER="smartems"
	[ -z "$SMARTEMS_GROUP" ] && SMARTEMS_GROUP="smartems"
	if ! getent group "$SMARTEMS_GROUP" > /dev/null 2>&1 ; then
	    addgroup --system "$SMARTEMS_GROUP" --quiet
	fi
	if ! id $SMARTEMS_USER > /dev/null 2>&1 ; then
	    adduser --system --home /usr/share/smartems --no-create-home \
		--ingroup "$SMARTEMS_GROUP" --disabled-password --shell /bin/false \
		"$SMARTEMS_USER"
	fi

	# Set user permissions on /var/log/smartems, /var/lib/smartems
	mkdir -p /var/log/smartems /var/lib/smartems
	chown -R $SMARTEMS_USER:$SMARTEMS_GROUP /var/log/smartems /var/lib/smartems
	chmod 755 /var/log/smartems /var/lib/smartems

  # copy user config files
  if [ ! -f $CONF_FILE ]; then
    cp /usr/share/smartems/conf/sample.ini $CONF_FILE
    cp /usr/share/smartems/conf/ldap.toml /etc/smartems/ldap.toml
  fi

  if [ ! -d $PROVISIONING_CFG_DIR ]; then
    mkdir -p $PROVISIONING_CFG_DIR/dashboards $PROVISIONING_CFG_DIR/datasources
    cp /usr/share/smartems/conf/provisioning/dashboards/sample.yaml $PROVISIONING_CFG_DIR/dashboards/sample.yaml
    cp /usr/share/smartems/conf/provisioning/datasources/sample.yaml $PROVISIONING_CFG_DIR/datasources/sample.yaml
  fi

  if [ ! -d $PROVISIONING_CFG_DIR/notifiers ]; then
    mkdir -p $PROVISIONING_CFG_DIR/notifiers
    cp /usr/share/smartems/conf/provisioning/notifiers/sample.yaml $PROVISIONING_CFG_DIR/notifiers/sample.yaml
  fi

	# configuration files should not be modifiable by smartems user, as this can be a security issue
	chown -Rh root:$SMARTEMS_GROUP /etc/smartems/*
	chmod 755 /etc/smartems
	find /etc/smartems -type f -exec chmod 640 {} ';'
	find /etc/smartems -type d -exec chmod 755 {} ';'

  # If $1=configure and $2 is set, this is an upgrade
  if [ "$2" != "" ]; then
    IS_UPGRADE=true
  fi

  if [ "x$IS_UPGRADE" != "xtrue" ]; then
    if command -v systemctl >/dev/null; then
      echo "### NOT starting on installation, please execute the following statements to configure smartems to start automatically using systemd"
      echo " sudo /bin/systemctl daemon-reload"
      echo " sudo /bin/systemctl enable smartems-server"
      echo "### You can start smartems-server by executing"
      echo " sudo /bin/systemctl start smartems-server"
    elif command -v update-rc.d >/dev/null; then
      echo "### NOT starting smartems-server by default on bootup, please execute"
      echo " sudo update-rc.d smartems-server defaults 95 10"
      echo "### In order to start smartems-server, execute"
      echo " sudo service smartems-server start"
    fi
  elif [ "$RESTART_ON_UPGRADE" = "true" ]; then

    echo -n "Restarting smartems-server service..."

    if command -v systemctl >/dev/null; then
      systemctl daemon-reload
      systemctl restart smartems-server || true
    elif [ -x /etc/init.d/smartems-server ]; then
      if command -v invoke-rc.d >/dev/null; then
        invoke-rc.d smartems-server restart || true
      else
        /etc/init.d/smartems-server restart || true
      fi
    fi
    echo " OK"

	fi
	;;
esac
