  mssqltests:
    build:
      context: docker/blocks/mssql/build
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password!
      MSSQL_PID: Express
      MSSQL_DATABASE: smartemstest
      MSSQL_USER: smartems
      MSSQL_PASSWORD: Password!
    ports:
      - "1433:1433"