#!/bin/sh

set -e

[ -f /etc/sysconfig/smartems-server ] && . /etc/sysconfig/smartems-server

startGrafana() {
  if [ -x /bin/systemctl ] ; then
    /bin/systemctl daemon-reload
		/bin/systemctl start smartems-server.service
	elif [ -x /etc/init.d/smartems-server ] ; then
		/etc/init.d/smartems-server start
	elif [ -x /etc/rc.d/init.d/smartems-server ] ; then
		/etc/rc.d/init.d/smartems-server start
	fi
}

stopGrafana() {
	if [ -x /bin/systemctl ] ; then
		/bin/systemctl stop smartems-server.service > /dev/null 2>&1 || :
	elif [ -x /etc/init.d/grafana-service ] ; then
		/etc/init.d/grafana-service stop
	elif [ -x /etc/rc.d/init.d/grafana-service ] ; then
		/etc/rc.d/init.d/grafana-service stop
	fi
}


# Initial installation: $1 == 1
# Upgrade: $1 == 2, and configured to restart on upgrade
if [ $1 -eq 1 ] ; then
	[ -z "$SMARTEMS_USER" ] && SMARTEMS_USER="grafana"
	[ -z "$SMARTEMS_GROUP" ] && SMARTEMS_GROUP="grafana"
	if ! getent group "$SMARTEMS_GROUP" > /dev/null 2>&1 ; then
    groupadd -r "$SMARTEMS_GROUP"
	fi
	if ! getent passwd "$SMARTEMS_USER" > /dev/null 2>&1 ; then
    useradd -r -g grafana -d /usr/share/grafana -s /sbin/nologin \
    -c "grafana user" grafana
	fi

  # copy user config files
  if [ ! -f $CONF_FILE ]; then
    cp /usr/share/grafana/conf/sample.ini $CONF_FILE
    cp /usr/share/grafana/conf/ldap.toml /etc/grafana/ldap.toml
  fi

  if [ ! -d $PROVISIONING_CFG_DIR ]; then
    mkdir -p $PROVISIONING_CFG_DIR/dashboards $PROVISIONING_CFG_DIR/datasources
    cp /usr/share/grafana/conf/provisioning/dashboards/sample.yaml $PROVISIONING_CFG_DIR/dashboards/sample.yaml
    cp /usr/share/grafana/conf/provisioning/datasources/sample.yaml $PROVISIONING_CFG_DIR/datasources/sample.yaml
  fi

  if [ ! -d $PROVISIONING_CFG_DIR/notifiers ]; then
    mkdir -p $PROVISIONING_CFG_DIR/notifiers
    cp /usr/share/grafana/conf/provisioning/notifiers/sample.yaml $PROVISIONING_CFG_DIR/notifiers/sample.yaml
  fi

 	# Set user permissions on /var/log/grafana, /var/lib/grafana
	mkdir -p /var/log/grafana /var/lib/grafana
	chown -R $SMARTEMS_USER:$SMARTEMS_GROUP /var/log/grafana /var/lib/grafana
	chmod 755 /var/log/grafana /var/lib/grafana

	# configuration files should not be modifiable by grafana user, as this can be a security issue
	chown -Rh root:$SMARTEMS_GROUP /etc/grafana/*
	chmod 755 /etc/grafana
	find /etc/grafana -type f -exec chmod 640 {} ';'
	find /etc/grafana -type d -exec chmod 755 {} ';'

  if [ -x /bin/systemctl ] ; then
    echo "### NOT starting on installation, please execute the following statements to configure grafana to start automatically using systemd"
    echo " sudo /bin/systemctl daemon-reload"
    echo " sudo /bin/systemctl enable smartems-server.service"
    echo "### You can start smartems-server by executing"
    echo " sudo /bin/systemctl start smartems-server.service"
  elif [ -x /sbin/chkconfig ] ; then
    echo "### NOT starting smartems-server by default on bootup, please execute"
    echo " sudo /sbin/chkconfig --add smartems-server"
    echo "### In order to start smartems-server, execute"
    echo " sudo service smartems-server start"
  fi
elif [ $1 -ge 2 ] ; then
  if [ "$RESTART_ON_UPGRADE" == "true" ]; then
    stopGrafana
    startGrafana
  fi
fi
