#!/bin/sh

set -e

echo "POSTTRANS: Running script"

[ -f /etc/sysconfig/smartems-server ] && . /etc/sysconfig/smartems-server

# copy config files if missing
if [ ! -f /etc/smartems/smartems.ini ]; then
  echo "POSTTRANS: Config file not found"

  if [ -f /etc/smartems/smartems.ini.rpmsave ]; then
    echo "POSTTRANS: /etc/smartems/smartems.ini.rpmsave config file found."
    mv /etc/smartems/smartems.ini.rpmsave /etc/smartems/smartems.ini
    echo "POSTTRANS: /etc/smartems/smartems.ini restored"

    if [ -f /etc/smartems/ldap.toml.rpmsave ]; then
      echo "POSTTRANS: /etc/smartems/ldap.toml.rpmsave found"
      mv /etc/smartems/ldap.toml.rpmsave /etc/smartems/ldap.toml
      echo "POSTTRANS: /etc/smartems/ldap.toml restored"
    fi

    echo "POSTTRANS: Restoring config file permissions"
    chown -Rh root:$SMARTEMS_GROUP /etc/smartems/*
    chmod 755 /etc/smartems
    find /etc/smartems -type f -exec chmod 640 {} ';'
    find /etc/smartems -type d -exec chmod 755 {} ';'
  fi
fi


