  openldap:
    container_name: ldap
    build: docker/blocks/openldap
    environment:
      SLAPD_PASSWORD: smartems
      SLAPD_DOMAIN: smartems.org
      SLAPD_ADDITIONAL_MODULES: memberof
    ports:
      - "389:389"


