  mysql:
    image: mysql:${mysql_version}
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: smartems
      MYSQL_USER: smartems
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb_monitor_enable=all]

  fake-mysql-data:
    image: smartems/fake-data-gen
    network_mode: bridge
    environment:
      FD_DATASOURCE: mysql
      FD_PORT: 3306

