FROM ubuntu

ARG REPO_CONFIG=smartems.list.oss
ARG PACKAGE=smartems

COPY sources.list /etc/apt/sources.list
RUN apt update && \
    apt install -y curl                \
                   apt-transport-https \
                   ca-certificates     \
                   gnupg               && \
    curl https://packages.smartems.com/gpg.key | apt-key add -

COPY "./$REPO_CONFIG" /etc/apt/sources.list.d/smartems.list
RUN apt update && \
    apt install -y $PACKAGE
